baseurl = "/"
languageCode = "en-us"
title = "Desmond Tuiyot"
theme = "hugo-sugoi"
googleAnalytics = ""
disqusShortname = "https-desmondtuiyot-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# what are these for?
summaryLength = 20
paginate = 5

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]

    favicon = "images/icons/favicon.png"
    herotitle = "Desmond Tuiyot"
    herotext = "Notes On Things I've Learnt And Projects I'm Working On"
    contact = "Send me a message and I will get back as soon as possible."
    
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

[hero]

[menu]
    [[menu.nav]]
        name    = "about"
        pre = "<i class='fas fa-home'></i>"
        url     = "/about/"
        weight  = -1
    [[menu.nav]]
        name    = "blog"
        pre = "<i class='fas fa-list'></i>"
        url     = "/post/"
        weight  = -2
#    [[menu.nav]]
#        name    = "contact"
#       pre = "<i class='fas fa-envelope'></i>"
#        url     = "contact"
#        weight  = -3   

    [[menu.nav]]
        name = "GitHub"
        url = "https://github.com/desmond-tuiyot"
        weight = -4
    [[menu.nav]]
        name = "Twitter"
        url = "https://twitter.com/desmond_tuiyot"
        weight = -5
    [[menu.nav]]
        name = "LinkedIn"
        url = "https://linkedin.com/desmond-tuiyot"
        weight = -6

