baseurl = "/"
languageCode = "en-us"
title = "Desmond Tuiyot"
theme = "hugo-erblog"
googleAnalytics = ""
disqusShortname = "https-desmondtuiyot-com"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/ThaNyneTray"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/ThaNyneTray"

[params]
    author = "Desmond Tuiyot"
    portrait = "image/desmond.png"
    description = "Aspiring Software Engineer/Data Analyst"
    bio = '''Hi. I'm a recent Computer Science graduate at Colgate University,
            with an interest in Software Engineering and Data Analysis. 
            I intend to document my projects and anything I learn in this blog'''
    
    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "image/desmond.png"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
    
    
    

