---
title: International Scholars Inc.
author: Desmond Tuiyot
date: '2020-08-10'
slug: international-scholars-inc
categories: []
tags:
  - plan
  - intl-scholars
---

## The WhatsApp Intergration

* From the example, it seems what we essentially need to do is create and deploy an app that would schedule and send reminders to complete an application to applicants. 
  * To send the reminders, we use Twilio, with Python & Flask. In this case, we don't really need a webapp since we're not planning to respond to any messages for now.
* We also need to somehow import data from the Excel sheet and add it to a database. After which we can simply step through all the records, and if there are NULL fields then we send a reminder to the person to actually finish the application. 

## Game plan

1. Need to create the program/webapp to send the whatsapp messages
  + I'm expecting a list of phone numbers to send reminders to
  + Probably a list of missing documents for each phone number - things they haven't submitted
2. Need to proces the data - messages are sent to WhatsApp conditionally. And the condition is whether someone has submitted the required documents.
  + Clean the data
  + Store it in SQL
  + Query the SQL to decide if and when to send the data
3. Data Aggregation

Creating new rows 
Updating the values - 


## Important Things to Do

* **ngrok** allows you to expose your local development server to the internet - but we can also just deploy on heroku and test there
  * For now we just need to silence the 

## Processing the Data: plan

**Initial Pass**

1. Get phone numbers, and submission dates from `part1.csv` - eliminate duplicates by latest submission date
2. Get docs from `part2.csv`
  * There are about 7 documents - passport, hs transcript, hs diploma, college transcript, college diploma, bank statement, and *others*
  * For the first 6, there are two possible fields I need to combine. So starting from column 3 to 14.

* **Transferring Data into SQL**

* There's a submission date field, which is from part1.csv. We use this to add new phone numbers
  * Essentially, include only the rows in the part1 dataframe that were submitted later than the most recent submission date in the database
* **Question:** How should the part2 data be added? 2 ways
  * Add it separately from the part1 data. **How?**
    * After updating the phone numbers, fetch the records with phone numbers that appear in part2. Then loop through that, updating the respective fields, and then commit after the for loop.

* **08/19/2020 Agenda**
  * Add names to db models
    * **DONE** - added `first_name` and `last_name` columns to the table. 
    * Migrations done as well.
  * Modify data manager code to handle names as well - **DONE**
    * Modify the data processing functions - **DONE**
  * Find a way to verify the phone numbers
  * Try to integrate this with the whatsapp code
    
* **Validating Phone Numbers**
  * **Problems**
    * The immediate problem is invalid phone numbers. 
      * We need phone numbers with the country code prefixed. In order to validate this, I would need the country as well (or at least, it would help).
      * There's also some numbers prefixed with 0's or with a minus sign.
    * However, not all values in the `country` column are filled/correct.
    * So I need a way to infer the country, to then use it to validate the phone number. 
  * **Solution**
    * **main tool:** pandas, twilio lookup
    * First, I need to filter out the country names that are in fact correct
    * For the remaining ones, I should manually check the city or the phone number to ascertain where it's at










