---
title: SQLAlchemy - the basics
author: Desmond Tuiyot
date: '2020-08-17'
slug: sqlalchemy-the-basics
categories: []
tags:
  - sqlalchemy
  - dbapi
  - orm
  - postgresql
---


# Introduction to SQLAlchemy
## sQLAlchemy

* There's 3 ways of interacting with database data in SQLAlchemy:
  1. Raw SQL
  2. SQL Expression Language
  3. ORM
* SQLAlchemy allows developers to use pure sql, unlike other ORMs.
* The SQL Expression API allows us to build sql queries using Python objects and operators - it is an abstraction over pure sql and abstracts away various implementation differences between databases. 
* The SQLAlchemy ORM is built on SQL Expression Language and allows us to associate Python classes to database tables. 

## SQLAlchemy Components

* **Engine** is the starting point of an SQLAlchemy application
  * It works with the **Connection pool** and the **Dialect** component to communicate SQL statements from SQLAlchemy to the database. 
  * It is created using `create_engine()` function and can used to directly interact with a database or can be passed to a **Session** object to work with an ORM
* **Dialect** is the system SQLAlchemy uses to communicate with various DBAPI implementations and databases. 
  * SQLAlchemy has dialects for many popular database systems - including PostgreSQL, which we use
* **MetaData** are Python objects that decribes `Table`s, `Column`s, `ForeignKey`s, and other schema-level objects
  * They can be expressed by explicitly naming the various components (as above) and their properties. 
  * MetaData can be easily generated by SQLAlchemy through a process called *reflection*.
* **Session** is the primary interface for persistence operations inside the ORM.
  * The Session object establishes all communication with the database and is a container for all objects loaded or associated with it throughout its lifespan 
  * It also provides an entry point into the *Query* object which allows you to run sql statements, where results are stored in the Session as Python objects. 
  
## Installations

* Installing SQLAlchemy, as well as the DBAPI drivers for *postgreSQL* and *MySQL*
  ```{eval=F}
  pip install sqlalchemy
  pip install psycopg2
  sudo apt-get install python-mysqldb
  ```
* Installing the PostgreSQL and MySQL servers
  ```{eval=F}
  sudo apt-get install mysql_server
  sudo apt-get install postgresql
  ```
* Install the *sqlite3* cli (sqlite module is distribute with Python)
  ```{eval=F}
  sudo apt-get install sqlite3
  ```

## SQLAlchemy Schema Definition Language

## SQLAlchemy Expression Language

## Object Relational Mapper in SQLAlchemy

* **Object Relational Mapping**
  * This is, in a sense, a solution to a problem that emerges when you have to use Python and SQL together. 
  * While Python database APIs grant us full and direct access to databases, we end up mixing Python and SQL together: this makes it harder to test and maintain SQL statements
  * It also goes against the idea of separation of concerns, where we want to separate *business logic* from *data access* and from the *presentation*
  * There is also the issue of *object-relational impedance mismatch*, which is a set of conceptual and technical difficulties that arise when a relational database is being used by an application that's written in OOP style. 
    * That is, python stores data in objects while SQL does so in tables: the conversion between those two ways of handling data presents a problem which isn't even part of the original problem.
* **SQLAlchemy ORM**
  * The SQLAlchemy OBject Relational Mapper maps 
    1. Python classes to database tables
    2. Instance variables/attributes to table columns
    3. Instance objects to table rows
  * In ORMs, the configurational process involves first describing the tables that we'll be working with, and then creating classes that will be mapped to these tables.
  * Modern SQLAlchemy uses a *Declarative* system to perform both these tasks together, by allowing us to create classes that contain directives to describe the database tables that they will be mapped to.
  * These classes are defined in terms of a base class known as a *declarative base class* that maintains a catalog of the tables and classes relative to that base. 
* After creating the configurations, we create a session. Remember that a *Session* component is the primary interface for persistence operations in the SQLAlchemy ORM. 





# References

1. [Zetcode SQLAlchemy Tutorial](http://zetcode.com/db/sqlalchemy/)
2. [TutorialsPoint SQLAlchemy Tutorial](https://www.tutorialspoint.com/sqlalchemy/sqlalchemy_introduction.htm)